use std::path::Path;

/// Controls how passthrough entries are generated by auto-detection.
#[derive(Clone, Copy)]
pub enum PassthroughMode {
    /// May include glob patterns (e.g. `"make *"`).
    Relaxed,
    /// Exact commands only. No globs allowed.
    Paranoid,
}

/// A build system that can be auto-detected in a project.
pub trait BuildSystem {
    fn name(&self) -> &'static str;
    fn detect(&self, root: &Path) -> bool;
    fn passthrough(&self, mode: PassthroughMode, root: &Path) -> Vec<String>;
}

fn all_detectors() -> Vec<Box<dyn BuildSystem>> {
    vec![
        Box::new(gnumake::GnuMake),
        Box::new(cargo::Cargo),
        Box::new(npm::Npm),
        Box::new(python::Python),
        Box::new(go::Go),
        Box::new(cmake::CMake),
        Box::new(gradle::Gradle),
        Box::new(maven::Maven),
        Box::new(meson::Meson),
    ]
}

/// Scan a project root for known build systems and return passthrough entries.
pub fn scan(root: &Path, mode: PassthroughMode) -> Vec<String> {
    let mut entries = Vec::new();
    for detector in all_detectors() {
        if detector.detect(root) {
            entries.extend(detector.passthrough(mode, root));
        }
    }
    entries
}

mod cargo;
mod cmake;
mod gnumake;
mod go;
mod gradle;
mod maven;
mod meson;
mod npm;
mod python;

#[cfg(test)]
#[path = "ut.rs"]
mod buildsys_tests;
